name: C++ CI Build & Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    # Step 1: Configure CMake
    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    # Step 2: Build the Code using CMake
    - name: Build the Code
      run: cmake --build build --config Release

    # Step 3a: Run the Demo (Linux)
    - name: Run the Demo (Linux)
      if: runner.os == 'Linux'
      run: ./build/adas_demo

    # Step 3b: Run the Demo (Windows)
    - name: Run the Demo (Windows)
      if: runner.os == 'Windows'
      run: ./build/Release/adas_demo.exe