name: C++ CI Build & Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    # Step 1: Configure CMake
    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    # Step 2: Build the Code using CMake
    - name: Build the Code
      run: cmake --build build --config Release

    # Step 3a: Run the Demo (Linux)
    - name: Run the Demo (Linux)
      if: runner.os == 'Linux'
      run: ./build/adas_demo

    # Step 3b: Run the Demo (Windows)
    - name: Run the Demo (Windows)
      if: runner.os == 'Windows'
      run: ./build/Release/adas_demo.exe

    # We must save the files so the Release job can find them later
    - name: Upload Linux Binary
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: adas_demo_linux
        path: build/adas_demo
        retention-days: 5

    - name: Upload Windows Executable
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: adas_demo_windows
        path: build/Release/adas_demo.exe
        retention-days: 5

  release:
    needs: build # Wait for the 'build' job to finish compiling
    runs-on: ubuntu-latest
    # ONLY run this job if the user pushed a 'v*' tag
    if: startsWith(github.ref, 'refs/tags/') 
    
    steps:
      - name: Download all compiled binaries
        uses: actions/download-artifact@v4
        with:
          path: final_release_files
          merge-multiple: true # Puts Windows and Linux files in the same folder

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: final_release_files/**/* # Uses wildcards to guarantee it finds the .exe
          generate_release_notes: true